import fs from "node:fs";
import { listOpen, listFixed } from "./storage.js";
import { SEVERITY_RANK } from "./types.js";
import type { Paths } from "./paths.js";

const HEADER = `# Claude Issues — Project Ledger

> This file is auto-generated by \`claude-issues\`. Do not edit by hand;
> changes will be overwritten on the next CLI write.
>
> **For Claude:** read this file first to see what's open vs. fixed in this
> project. Use \`claude-issues show <id>\` for full details on any issue.
> Use \`claude-issues note <id> "..."\` to record progress, and
> \`claude-issues fix <id>\` when you've verified a fix.
`;

export function regenerateIndex(paths: Paths): void {
  const open = listOpen(paths).sort(
    (a, b) =>
      SEVERITY_RANK[a.frontmatter.severity] -
        SEVERITY_RANK[b.frontmatter.severity] ||
      a.frontmatter.id.localeCompare(b.frontmatter.id),
  );
  const fixed = listFixed(paths)
    .sort((a, b) =>
      (b.frontmatter.fixed_at ?? "").localeCompare(a.frontmatter.fixed_at ?? ""),
    )
    .slice(0, 10);

  let out = HEADER + "\n## Open issues\n\n";
  if (open.length === 0) {
    out += "_None._\n";
  } else {
    out += "| ID | Title | Severity | Files |\n";
    out += "|----|-------|----------|-------|\n";
    for (const i of open) {
      const files = i.frontmatter.files?.join(", ") || "";
      out += `| ${i.frontmatter.id} | ${escape(i.frontmatter.title)} | ${i.frontmatter.severity} | ${escape(files)} |\n`;
    }
  }

  out += "\n## Recently fixed (last 10)\n\n";
  if (fixed.length === 0) {
    out += "_None._\n";
  } else {
    out += "| ID | Title | Fixed |\n";
    out += "|----|-------|-------|\n";
    for (const i of fixed) {
      const when = i.frontmatter.fixed_at?.slice(0, 10) ?? "";
      out += `| ${i.frontmatter.id} | ${escape(i.frontmatter.title)} | ${when} |\n`;
    }
  }

  fs.writeFileSync(paths.index, out, "utf8");
}

function escape(s: string): string {
  return s.replace(/\|/g, "\\|");
}
