import fs from "node:fs";
import { listOpen, listFixed, listArchive } from "./storage.js";
import { SEVERITY_RANK, type Issue } from "./types.js";
import type { Paths } from "./paths.js";

const HEADER = `# Claude Issues — Project Ledger

> This file is auto-generated by \`claude-issues\`. Do not edit by hand;
> changes will be overwritten on the next CLI write.
>
> **For Claude:** read this file first to see what's open, fixed, or
> archived in this project. Use \`claude-issues show <id>\` for full
> details. Before fixing anything, scan the "Fixed" and "Archive"
> sections for prior work touching the same files — see SKILL.md.
`;

export function regenerateIndex(paths: Paths): void {
  const open = listOpen(paths).sort(
    (a, b) =>
      SEVERITY_RANK[a.frontmatter.severity] -
        SEVERITY_RANK[b.frontmatter.severity] ||
      a.frontmatter.id.localeCompare(b.frontmatter.id),
  );
  const fixed = listFixed(paths)
    .sort((a, b) =>
      (b.frontmatter.fixed_at ?? "").localeCompare(a.frontmatter.fixed_at ?? ""),
    )
    .slice(0, 20);
  const archive = listArchive(paths).sort((a, b) =>
    (b.frontmatter.closed_at ?? b.frontmatter.fixed_at ?? "").localeCompare(
      a.frontmatter.closed_at ?? a.frontmatter.fixed_at ?? "",
    ),
  );

  let out = HEADER + "\n## Open issues\n\n";
  out += renderTableOpen(open);
  out += "\n## Fixed (last 20)\n\n";
  out += renderTableFixed(fixed);
  out += "\n## Archive (wontfix · superseded · duplicate)\n\n";
  out += renderTableArchive(archive);

  fs.writeFileSync(paths.index, out, "utf8");
}

function renderTableOpen(issues: Issue[]): string {
  if (issues.length === 0) return "_None._\n";
  let out = "| ID | Title | Severity | Files | Links |\n";
  out += "|----|-------|----------|-------|-------|\n";
  for (const i of issues) {
    out += `| ${i.frontmatter.id} | ${esc(i.frontmatter.title)} | ${i.frontmatter.severity} | ${esc(joinFiles(i))} | ${esc(linkSummary(i))} |\n`;
  }
  return out;
}

function renderTableFixed(issues: Issue[]): string {
  if (issues.length === 0) return "_None._\n";
  let out = "| ID | Title | Files | Fixed | Links |\n";
  out += "|----|-------|-------|-------|-------|\n";
  for (const i of issues) {
    const when = (i.frontmatter.fixed_at ?? "").slice(0, 10);
    out += `| ${i.frontmatter.id} | ${esc(i.frontmatter.title)} | ${esc(joinFiles(i))} | ${when} | ${esc(linkSummary(i))} |\n`;
  }
  return out;
}

function renderTableArchive(issues: Issue[]): string {
  if (issues.length === 0) return "_None._\n";
  let out = "| ID | Title | Status | Files | Closed | Links |\n";
  out += "|----|-------|--------|-------|--------|-------|\n";
  for (const i of issues) {
    const when = (i.frontmatter.closed_at ?? i.frontmatter.fixed_at ?? "").slice(0, 10);
    out += `| ${i.frontmatter.id} | ${esc(i.frontmatter.title)} | ${i.frontmatter.status} | ${esc(joinFiles(i))} | ${when} | ${esc(linkSummary(i))} |\n`;
  }
  return out;
}

function joinFiles(i: Issue): string {
  return i.frontmatter.files?.join(", ") ?? "";
}

function linkSummary(i: Issue): string {
  const parts: string[] = [];
  if (i.frontmatter.supersedes) parts.push(`supersedes ${i.frontmatter.supersedes}`);
  if (i.frontmatter.superseded_by) parts.push(`superseded by ${i.frontmatter.superseded_by}`);
  if (i.frontmatter.duplicate_of) parts.push(`dup of ${i.frontmatter.duplicate_of}`);
  if (i.frontmatter.related && i.frontmatter.related.length > 0) {
    parts.push(`related: ${i.frontmatter.related.join(", ")}`);
  }
  return parts.join("; ");
}

function esc(s: string): string {
  return s.replace(/\|/g, "\\|");
}
